### PR TITLE
Update loading_bar.js

### PR DESCRIPTION
**Pull request by ipostol**
add more settings to props

### CODE REVIEW

**Comment by ipostol** [comment]
please add props for customize loading-bar speed etc..

**Comment by mironov** [comment]
@ipostol Good idea!
Please add a spec for the change and I'll merge it.

**Comment by ipostol** [comment]
Sorry for many build fails, It was too lazy to clone repository :)

**Comment by mironov** [comment]
@ipostol Hey, I've incorporated your changes in https://github.com/mironov/react-redux-loading-bar/commit/0c3dc256062580eb85961c6e24b8658426f1a8a0 along with additional tests.
Thanks for the pull request!

**Pull request closed without merging**
